### ISSUE TITLE
dashboad does not work with zabbix 3.4 api

### ISSUE THREAD

**Issue by blka** [chojayr/dashing_zabbix#1]
data: {"title":"DASHBOARD IN ERROR : undefined method `keys' for #<Array:0x00000003a17720>","status":"disa-blink","id":"#dashboard#_text","updatedAt":1503411326}
